/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToast: typeof import('./src/components/AppToast.vue')['default']
    AuthModal: typeof import('./src/components/AuthModal.vue')['default']
    DepositModal: typeof import('./src/components/DepositModal.vue')['default']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HomeFreeResourceBoard: typeof import('./src/components/home/HomeFreeResourceBoard.vue')['default']
    HomeHeroSection: typeof import('./src/components/home/HomeHeroSection.vue')['default']
    HomeSummarySection: typeof import('./src/components/home/HomeSummarySection.vue')['default']
    PublishModal: typeof import('./src/components/PublishModal.vue')['default']
    ResourceCatalog: typeof import('./src/components/ResourceCatalog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
